import { Prisma } from '@prisma/client';
import { computedBookingStatus, rentalDays } from '../utils/rental';
import { toDocumentAssetDto } from '../documents/document-storage.service';

type AnyRecord = Record<string, any>;
function decimalToNumber(value: any) { return value instanceof Prisma.Decimal ? value.toNumber() : value; }
function dateToIso(value: any) { return value instanceof Date ? value.toISOString() : value; }
function clean<T extends AnyRecord>(obj: T): T { return Object.fromEntries(Object.entries(obj).map(([key, value]) => [key, dateToIso(decimalToNumber(value))])) as T; }
function mileagePackageDailyKm(item: any): number | null | undefined {
  if (!item?.nome) return undefined;
  const normalized = String(item.nome).trim().toLowerCase();
  if (normalized.includes('illimit')) return null;
  const match = normalized.match(/(\d+)/);
  return match ? Number(match[1]) : undefined;
}

export function toClientDto(client: any) { if (!client) return client; return clean({ id: client.id, nome: client.nome, cognome: client.cognome, sesso: client.sesso, dataNascita: client.dataNascita, luogoNascita: client.luogoNascita, codiceFiscale: client.codiceFiscale, indirizzoResidenza: client.indirizzoResidenza, luogoRilascioCartaIdentita: client.luogoRilascioCartaIdentita, numeroCartaIdentita: client.numeroCartaIdentita, dataRilascioCartaIdentita: client.dataRilascioCartaIdentita, dataScadenzaCartaIdentita: client.dataScadenzaCartaIdentita, luogoRilascioPatente: client.luogoRilascioPatente, numeroPatente: client.numeroPatente, dataRilascioPatente: client.dataRilascioPatente, dataScadenzaPatente: client.dataScadenzaPatente, telefono: client.telefono, email: client.email, createdAt: client.createdAt, createdBy: client.createdBy, updatedAt: client.updatedAt, updatedBy: client.updatedBy, deletedAt: client.deletedAt, deletedBy: client.deletedBy }); }
export function toBillingDataDto(item: any) { if (!item) return item; return clean({ id: item.id, clienteId: item.clienteId, cliente: item.cliente ? toClientDto(item.cliente) : undefined, partitaIva: item.partitaIva, codiceFiscale: item.codiceFiscale, ragioneSociale: item.ragioneSociale, indirizzoSedeLegale: item.indirizzoSedeLegale, codiceUnivoco: item.codiceUnivoco, pec: item.pec, email: item.email, createdAt: item.createdAt, createdBy: item.createdBy, updatedAt: item.updatedAt, updatedBy: item.updatedBy, deletedAt: item.deletedAt, deletedBy: item.deletedBy }); }
export function toVehicleDto(vehicle: any) { if (!vehicle) return vehicle; return clean({ id: vehicle.id, tipo: vehicle.tipo, marca: vehicle.marca, modello: vehicle.modello, targa: vehicle.targa, dataImmatricolazione: vehicle.dataImmatricolazione, alimentazione: vehicle.alimentazione, costoGiornaliero: vehicle.costoGiornaliero, lunghezza: vehicle.lunghezza, larghezza: vehicle.larghezza, altezza: vehicle.altezza, lunghezzaInterna: vehicle.lunghezzaInterna, larghezzaInterna: vehicle.larghezzaInterna, altezzaInterna: vehicle.altezzaInterna, postiAuto: vehicle.postiAuto, metodoAcquisto: vehicle.metodoAcquisto, canoneMensile: vehicle.canoneMensile, importoVeicolo: vehicle.importoVeicolo, franchigiaRca: vehicle.franchigiaRca, franchigiaRcaTipo: vehicle.franchigiaRcaTipo, franchigiaKasko: vehicle.franchigiaKasko, franchigiaKaskoTipo: vehicle.franchigiaKaskoTipo, scopertoFurtoIncendio: vehicle.scopertoFurtoIncendio, scopertoFurtoIncendioTipo: vehicle.scopertoFurtoIncendioTipo, compagniaAssicurativa: vehicle.compagniaAssicurativa, dataScadenzaAssicurazione: vehicle.dataScadenzaAssicurazione, importoAssicurazione: vehicle.importoAssicurazione, stato: vehicle.stato, kmAttuali: vehicle.kmAttuali, createdAt: vehicle.createdAt, createdBy: vehicle.createdBy, updatedAt: vehicle.updatedAt, updatedBy: vehicle.updatedBy, deletedAt: vehicle.deletedAt, deletedBy: vehicle.deletedBy }); }
export function toCoverageDto(coverage: any) { if (!coverage) return coverage; return clean({ id: coverage.id, nome: coverage.nome, costoImportoFisso: coverage.costoImportoFisso, costoPercentuale: coverage.costoPercentuale, costo: coverage.costo, costoTipo: coverage.costoTipo, franchigiaRca: coverage.franchigiaRca, franchigiaRcaTipo: coverage.franchigiaRcaTipo, franchigiaKasko: coverage.franchigiaKasko, franchigiaKaskoTipo: coverage.franchigiaKaskoTipo, franchigiaFurtoIncendio: coverage.franchigiaFurtoIncendio, scopertoFurtoIncendio: coverage.scopertoFurtoIncendio, scopertoFurtoIncendioTipo: coverage.scopertoFurtoIncendioTipo, createdAt: coverage.createdAt, createdBy: coverage.createdBy, updatedAt: coverage.updatedAt, updatedBy: coverage.updatedBy }); }
export function toMileagePackageDto(item: any) { if (!item) return item; return clean({ id: item.id, nome: item.nome, chilometraggio: item.chilometraggio, costoImportoFisso: item.costoImportoFisso, costoPercentuale: item.costoPercentuale, costo: item.costo, costoTipo: item.costoTipo, attivo: item.attivo, createdAt: item.createdAt, createdBy: item.createdBy, updatedAt: item.updatedAt, updatedBy: item.updatedBy }); }
export function toAdditionalServiceDto(item: any) { if (!item) return item; return clean({ id: item.id, nome: item.nome, descrizione: item.descrizione, costoImportoFisso: item.costoImportoFisso, costoPercentuale: item.costoPercentuale, costo: item.costo, costoTipo: item.costoTipo, attivo: item.attivo, createdAt: item.createdAt, createdBy: item.createdBy, updatedAt: item.updatedAt, updatedBy: item.updatedBy }); }
export function toRentalSettingsDto(item: any) { if (!item) return null; return clean({ companyId: item.companyId, costoConducenteAggiuntivoImportoFisso: item.costoConducenteAggiuntivoImportoFisso, costoConducenteAggiuntivoPercentuale: item.costoConducenteAggiuntivoPercentuale, costoConducenteAggiuntivo: item.costoConducenteAggiuntivo, costoConducenteAggiuntivoTipo: item.costoConducenteAggiuntivoTipo, cauzioneStandard: item.cauzioneStandard, costoKmEccedenza: item.costoKmEccedenza, penaleCarburante: item.penaleCarburante, contractLogo: item.contractLogo ? toDocumentAssetDto(item.contractLogo) : null, contractStamp: item.contractStamp ? toDocumentAssetDto(item.contractStamp) : null, createdAt: item.createdAt, createdBy: item.createdBy, updatedAt: item.updatedAt, updatedBy: item.updatedBy }); }
export function toOperatorDto(operator: any) { if (!operator) return operator; return clean({ id: operator.id, nome: operator.nome, cognome: operator.cognome, telefono: operator.telefono, email: operator.email, hasAccount: Boolean(operator.accountId), attivo: operator.attivo, createdAt: operator.createdAt, createdBy: operator.createdBy, updatedAt: operator.updatedAt, updatedBy: operator.updatedBy }); }

export function toBookingDto(booking: any) {
  if (!booking) return booking;
  let giorniNoleggio: number | undefined; let kmFineCalcolato: number | undefined;
  try {
    giorniNoleggio = rentalDays(booking.dataInizioContratto, booking.dataFineContratto);
    const kmGiornalieri = mileagePackageDailyKm(booking.mileagePackage);
    kmFineCalcolato = booking.kmInizio != null && typeof kmGiornalieri === 'number' ? booking.kmInizio + kmGiornalieri * giorniNoleggio : undefined;
  } catch (_) { giorniNoleggio = undefined; }
  return clean({ id: booking.id, clienteId: booking.clienteId, veicoloId: booking.veicoloId, cliente: booking.cliente ? toClientDto(booking.cliente) : undefined, conducenteAggiuntivoId: booking.conducenteAggiuntivoId, conducenteAggiuntivo: booking.conducenteAggiuntivo ? toClientDto(booking.conducenteAggiuntivo) : undefined, billingDataId: booking.billingDataId, billingData: booking.billingData ? toBillingDataDto(booking.billingData) : undefined, veicolo: booking.veicolo ? toVehicleDto(booking.veicolo) : undefined, dataPrenotazione: booking.dataPrenotazione, dataEmissioneFattura: booking.dataEmissioneFattura, dataInizioContratto: booking.dataInizioContratto, dataFineContratto: booking.dataFineContratto, giorniNoleggio, prezzo: booking.prezzo, metodoPagamento: booking.metodoPagamento, mileagePackageId: booking.mileagePackageId, mileagePackage: booking.mileagePackage ? toMileagePackageDto(booking.mileagePackage) : undefined, nomeOperatore: booking.nomeOperatore, operatorId: booking.operatorId, operator: booking.operator ? toOperatorDto(booking.operator) : undefined, coperturaAssicurativa: booking.coperturaAssicurativa, coperturaAssicurativaId: booking.coperturaAssicurativaId, copertura: booking.copertura ? toCoverageDto(booking.copertura) : undefined, serviziAggiuntivi: booking.serviziAggiuntivi ? booking.serviziAggiuntivi.map((x: any) => toAdditionalServiceDto(x.additionalService)) : undefined, stato: computedBookingStatus(booking.stato, booking.dataInizioContratto, booking.dataFineContratto), statoSalvato: booking.stato, kmInizio: booking.kmInizio, kmFineCalcolato, note: booking.note, consegnaEffettuataAt: booking.consegnaEffettuataAt, importoCauzione: booking.importoCauzione, metodoPagamentoCauzione: booking.metodoPagamentoCauzione, codicePreautorizzazioneCauzione: booking.codicePreautorizzazioneCauzione, livelloCarburanteConsegna: booking.livelloCarburanteConsegna, kmConsegna: booking.kmConsegna, riconsegnaEffettuataAt: booking.riconsegnaEffettuataAt, livelloCarburanteRiconsegna: booking.livelloCarburanteRiconsegna, kmRiconsegna: booking.kmRiconsegna, cauzioneRestituita: booking.cauzioneRestituita, cauzioneTrattenuta: booking.cauzioneTrattenuta, noteRiconsegna: booking.noteRiconsegna, kmEccedenza: booking.kmEccedenza, importoPenaleKm: booking.importoPenaleKm, importoPenaleCarburante: booking.importoPenaleCarburante, importoPenali: booking.importoPenali, metodoPagamentoPenali: booking.metodoPagamentoPenali, createdAt: booking.createdAt, createdBy: booking.createdBy, updatedAt: booking.updatedAt, updatedBy: booking.updatedBy, deletedAt: booking.deletedAt, deletedBy: booking.deletedBy });
}

export function toDamageDto(damage: any) { if (!damage) return damage; return clean({ id: damage.id, veicoloId: damage.veicoloId, veicolo: damage.veicolo ? toVehicleDto(damage.veicolo) : undefined, stato: damage.stato, note: damage.note, x: damage.x, y: damage.y, dataAggiunta: damage.dataAggiunta, dataRiparazione: damage.dataRiparazione, createdAt: damage.createdAt, createdBy: damage.createdBy, updatedAt: damage.updatedAt, updatedBy: damage.updatedBy, deletedAt: damage.deletedAt, deletedBy: damage.deletedBy }); }
export function toFineDto(fine: any) { if (!fine) return fine; return clean({ id: fine.id, veicoloId: fine.veicoloId, bookingId: fine.bookingId, targa: fine.targa, dataMulta: fine.dataMulta, importo: fine.importo, dataNotifica: fine.dataNotifica, luogoInfrazione: fine.luogoInfrazione, dataRinotifica: fine.dataRinotifica, note: fine.note, veicolo: fine.veicolo ? toVehicleDto(fine.veicolo) : undefined, booking: fine.booking ? toBookingDto(fine.booking) : undefined, createdAt: fine.createdAt, createdBy: fine.createdBy, updatedAt: fine.updatedAt, updatedBy: fine.updatedBy, deletedAt: fine.deletedAt, deletedBy: fine.deletedBy }); }
export function toPaginatedDto<T>(result: { items: T[]; total: number; page: number; pageSize: number }, mapper: (item: T) => any) { return { items: result.items.map(mapper), total: result.total, page: result.page, pageSize: result.pageSize }; }
export function toCargosPortalConfigDto(item: any) {
  if (!item) return null;
  return clean({
    companyId: item.companyId,
    username: item.username,
    hasPassword: Boolean(item.passwordEncrypted),
    hasApiKey: Boolean(item.apiKeyEncrypted),
    createdAt: item.createdAt,
    createdBy: item.createdBy,
    updatedAt: item.updatedAt,
    updatedBy: item.updatedBy,
    deletedAt: item.deletedAt,
    deletedBy: item.deletedBy
  });
}
