export const ITALIAN_CITIES_BY_PROVINCE: Record<string, string[]> = {
  RM: ['Roma', 'Ostia', 'Fiumicino', 'Ciampino', 'Guidonia Montecelio', 'Tivoli', 'Pomezia', 'Anzio', 'Nettuno', 'Velletri', 'Frascati'],
  FR: ['Frosinone', 'Ferentino', 'Alatri', 'Anagni', 'Cassino', 'Ceccano', 'Sora', 'Veroli', 'Fiuggi'],
  LT: ['Latina', 'Aprilia', 'Terracina', 'Formia', 'Gaeta', 'Fondi', 'Sabaudia', 'Sperlonga'],
  VT: ['Viterbo', 'Tarquinia', 'Civita Castellana', 'Montefiascone', 'Vetralla'],
  RI: ['Rieti', 'Fara in Sabina', 'Poggio Mirteto', 'Amatrice'],
  MI: ['Milano', 'Sesto San Giovanni', 'Rho', 'Cinisello Balsamo', 'Legnano'],
  TO: ['Torino', 'Moncalieri', 'Rivoli', 'Collegno', 'Settimo Torinese'],
  NA: ['Napoli', 'Pozzuoli', 'Afragola', 'Casoria', 'Torre del Greco', 'Pompei'],
  BA: ['Bari', 'Altamura', 'Molfetta', 'Bitonto', 'Monopoli'],
  PA: ['Palermo', 'Bagheria', 'Monreale', 'Cefalu'],
  CA: ['Cagliari', 'Quartu Sant Elena', 'Selargius', 'Assemini'],
  SS: ['Sassari', 'Olbia', 'Alghero', 'Porto Torres'],
  FI: ['Firenze', 'Empoli', 'Scandicci', 'Sesto Fiorentino'],
  BO: ['Bologna', 'Imola', 'Casalecchio di Reno'],
  GE: ['Genova', 'Rapallo', 'Chiavari', 'Sestri Levante'],
  VE: ['Venezia', 'Mestre', 'Chioggia', 'Jesolo'],
  VR: ['Verona', 'Legnago', 'Villafranca di Verona'],
  PD: ['Padova', 'Abano Terme', 'Cittadella'],
  AN: ['Ancona', 'Senigallia', 'Jesi', 'Fabriano'],
  PE: ['Pescara', 'Montesilvano', 'Penne'],
  AQ: ['L Aquila', 'Avezzano', 'Sulmona'],
  SA: ['Salerno', 'Cava de Tirreni', 'Battipaglia', 'Paestum'],
  CE: ['Caserta', 'Aversa', 'Marcianise'],
  CT: ['Catania', 'Acireale', 'Misterbianco', 'Giarre'],
  ME: ['Messina', 'Taormina', 'Milazzo'],
  RC: ['Reggio Calabria', 'Villa San Giovanni', 'Locri'],
  CZ: ['Catanzaro', 'Lamezia Terme', 'Soverato']
};

export const CADASTRAL_CODES: Record<string, { code: string; province: string }> = {
  ROMA: { code: 'H501', province: 'RM' },
  OSTIA: { code: 'H501', province: 'RM' },
  FIUMICINO: { code: 'M297', province: 'RM' },
  FROSINONE: { code: 'D810', province: 'FR' },
  FERENTINO: { code: 'D539', province: 'FR' },
  LATINA: { code: 'E472', province: 'LT' },
  MILANO: { code: 'F205', province: 'MI' },
  TORINO: { code: 'L219', province: 'TO' },
  NAPOLI: { code: 'F839', province: 'NA' },
  BARI: { code: 'A662', province: 'BA' },
  PALERMO: { code: 'G273', province: 'PA' },
  CAGLIARI: { code: 'B354', province: 'CA' },
  SASSARI: { code: 'I452', province: 'SS' },
  OLBIA: { code: 'G015', province: 'SS' },
  FIRENZE: { code: 'D612', province: 'FI' },
  BOLOGNA: { code: 'A944', province: 'BO' },
  GENOVA: { code: 'D969', province: 'GE' },
  VENEZIA: { code: 'L736', province: 'VE' },
  VERONA: { code: 'L781', province: 'VR' },
  PADOVA: { code: 'G224', province: 'PD' },
  ANCONA: { code: 'A271', province: 'AN' },
  PESCARA: { code: 'G482', province: 'PE' },
  'L AQUILA': { code: 'A345', province: 'AQ' },
  SALERNO: { code: 'H703', province: 'SA' },
  CASERTA: { code: 'B963', province: 'CE' },
  CATANIA: { code: 'C351', province: 'CT' },
  MESSINA: { code: 'F158', province: 'ME' },
  'REGGIO CALABRIA': { code: 'H224', province: 'RC' },
  CATANZARO: { code: 'C352', province: 'CZ' }
};
