export const openApiSpec = {
  openapi: '3.0.3',
  info: { title: 'MoveMGMT Core MS API', version: '1.2.0', description: 'Microservizio multi-societa per autonoleggio: auth JWT, clienti, veicoli, prenotazioni, danni, configurazioni, dati fatturazione e multe' },
  servers: [{ url: 'http://localhost:3000' }],
  tags: [
    { name: 'Health' }, { name: 'Auth' }, { name: 'Clienti' }, { name: 'Veicoli' }, { name: 'Prenotazioni' }, { name: 'Danni' }, { name: 'Configurazione' }, { name: 'Dati fatturazione' }, { name: 'Multe' }, { name: 'Documenti' }, { name: 'Contratti' }
  ],
  security: [{ bearerAuth: [] }],
  paths: {
    '/health/live': { get: { tags: ['Health'], security: [], responses: { '200': { description: 'Processo attivo', content: { 'application/json': { schema: { type: 'object', properties: { status: { type: 'string', example: 'ok' } } } } } } } } },
    '/health/ready': { get: { tags: ['Health'], security: [], responses: { '200': { description: 'Servizio pronto' }, '503': { description: 'Servizio non pronto' } } } },
    '/health': { get: { tags: ['Health'], security: [], deprecated: true, responses: { '200': { description: 'Compatibilita temporanea live check' } } } },
    '/openapi.json': { get: { tags: ['Health'], security: [], responses: { '200': { description: 'OpenAPI JSON' } } } },
    '/auth/register': { post: { tags: ['Auth'], security: [], summary: 'Registrazione societa/account', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/RegisterRequest' } } } }, responses: { '201': { description: 'Account creato con token JWT' } } } },
    '/auth/login': { post: { tags: ['Auth'], security: [], summary: 'Login tramite email e password', requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/LoginRequest' } } } }, responses: { '200': { description: 'Token JWT' }, '401': { description: 'Credenziali non valide o account non attivo' } } } },
    '/clients': crud('Clienti', 'cliente', 'CreateClientRequest'), '/clients/{id}': crudById('Clienti', 'cliente', 'UpdateClientRequest'),
    '/clients/search/list': postBody('Clienti', 'Ricerca clienti OR su nome, cognome, telefono, codice fiscale', 'SearchTextRequest'),
    '/clients/generate-fiscal-code': postBody('Clienti', 'Genera codice fiscale', 'FiscalCodeRequest'),
    '/clients/addresses/autocomplete': postBody('Clienti', 'Autocomplete indirizzi residenza esistenti', 'AddressAutocompleteRequest'),
    '/vehicles': crud('Veicoli', 'veicolo', 'CreateVehicleRequest'), '/vehicles/{id}': crudById('Veicoli', 'veicolo', 'UpdateVehicleRequest'),
    '/vehicles/search/list': postBody('Veicoli', 'Ricerca veicoli OR su targa, marca, modello', 'SearchTextRequest'),
    '/vehicles/check-availability': postBody('Veicoli', 'Verifica disponibilita per targa e date/ore', 'VehicleDateRangeRequest'),
    '/vehicles/calculate-rental-price': postBody('Veicoli', 'Calcola prezzo indicativo noleggio', 'VehicleDateRangeRequest'),
    '/vehicles/available': postBody('Veicoli', 'Trova veicoli disponibili per tipo e date/ore', 'AvailableVehiclesRequest'),
    '/bookings': crud('Prenotazioni', 'prenotazione confermata', 'CreateBookingRequest'), '/bookings/{id}': crudById('Prenotazioni', 'prenotazione', 'UpdateBookingRequest'),
    '/bookings/drafts': postBody('Prenotazioni', 'Salva prenotazione in bozza', 'CreateBookingRequest'),
    '/bookings/{id}/cancel': { patch: { tags: ['Prenotazioni'], summary: 'Annulla prenotazione', parameters: [idParam()], responses: ok() } },
    '/bookings/{id}/delivery-defaults': { get: { tags: ['Prenotazioni'], summary: 'Recupera carburante e km da ultima riconsegna dello stesso veicolo', parameters: [idParam()], responses: ok() } },
    '/bookings/{id}/delivery': { patch: { tags: ['Prenotazioni'], summary: 'Registra consegna veicolo', parameters: [idParam()], requestBody: body('BookingDeliveryRequest'), responses: ok() } },
    '/bookings/{id}/return': { patch: { tags: ['Prenotazioni'], summary: 'Registra riconsegna veicolo', parameters: [idParam()], requestBody: body('BookingReturnRequest'), responses: ok() } },
    '/bookings/search/list': postBody('Prenotazioni', 'Ricerca prenotazioni avanzata', 'SearchBookingRequest'),
    '/bookings/find-by-fine': postBody('Prenotazioni', 'Trova prenotazione da targa e data multa', 'FindByFineRequest'),
    '/billing-data': crud('Dati fatturazione', 'dati fatturazione', 'CreateBillingDataRequest'), '/billing-data/{id}': crudById('Dati fatturazione', 'dati fatturazione', 'UpdateBillingDataRequest'),
    '/billing-data/search/list': postBody('Dati fatturazione', 'Ricerca dati fatturazione', 'SearchBillingDataRequest'),
    '/fines': crud('Multe', 'multa', 'CreateFineRequest'), '/fines/{id}': crudById('Multe', 'multa', 'UpdateFineRequest'),
    '/fines/search/list': postBody('Multe', 'Ricerca multe', 'SearchFineRequest'),
    '/vehicles/{vehicleId}/damages': { get: { tags: ['Danni'], parameters: [{ name: 'vehicleId', in: 'path', required: true, schema: { type: 'string' } }], responses: ok() }, post: { tags: ['Danni'], summary: 'Aggiungi danno con coordinate x/y in pixel', parameters: [{ name: 'vehicleId', in: 'path', required: true, schema: { type: 'string' } }], requestBody: body('CreateDamageRequest'), responses: created() } },
    '/vehicle-damages/search/list': postBody('Danni', 'Ricerca danni', 'SearchDamageRequest'),
    '/vehicle-damages/{id}/repair': { patch: { tags: ['Danni'], parameters: [idParam()], responses: ok() } },
    '/vehicle-damages/{id}': crudById('Danni', 'danno', 'UpdateDamageRequest'),
    '/setup/insurance-coverages': crud('Configurazione', 'copertura assicurativa', 'CreateCoverageRequest'), '/setup/insurance-coverages/{id}': patchOnly('Configurazione', 'copertura assicurativa', 'UpdateCoverageRequest'),
    '/setup/mileage-packages': crud('Configurazione', 'chilometraggio giornaliero', 'CreateMileagePackageRequest'), '/setup/mileage-packages/{id}': patchOnly('Configurazione', 'chilometraggio giornaliero', 'UpdateMileagePackageRequest'),
    '/setup/additional-services': crud('Configurazione', 'servizio aggiuntivo', 'CreateAdditionalServiceRequest'), '/setup/additional-services/{id}': patchOnly('Configurazione', 'servizio aggiuntivo', 'UpdateAdditionalServiceRequest'),
    '/setup/rental-settings': { get: { tags: ['Configurazione'], summary: 'Recupera impostazioni noleggio', responses: ok() }, put: { tags: ['Configurazione'], summary: 'Configura costo conducente aggiuntivo', requestBody: body('RentalSettingsRequest'), responses: ok() } },
    '/setup/cargos-config': { get: { tags: ['Configurazione'], summary: 'Recupera configurazione portale CARGOS', responses: ok() }, put: { tags: ['Configurazione'], summary: 'Crea o sostituisce configurazione portale CARGOS', requestBody: body('CargosPortalConfigRequest'), responses: ok() }, patch: { tags: ['Configurazione'], summary: 'Modifica parziale configurazione portale CARGOS', requestBody: body('UpdateCargosPortalConfigRequest'), responses: ok() }, delete: { tags: ['Configurazione'], summary: 'Elimina logicamente configurazione portale CARGOS', responses: ok() } },
    '/setup/operators': crud('Configurazione', 'operatore', 'CreateOperatorRequest'),
    '/setup/configuration': { get: { tags: ['Configurazione'], summary: 'Configurazione unica completa', responses: ok() } },
    '/documents': { get: { tags: ['Documenti'], summary: 'Lista documenti salvati', parameters: [queryParam('type'), queryParam('bookingId'), queryParam('clientId'), queryParam('contractDocumentId')], responses: ok() }, post: { tags: ['Documenti'], summary: 'Salva un documento generico su storage documentale', requestBody: { required: true, content: { 'multipart/form-data': { schema: { $ref: '#/components/schemas/SaveDocumentMultipartRequest' } }, 'application/json': { schema: { $ref: '#/components/schemas/SaveDocumentJsonRequest' } } } }, responses: created() } },
    '/documents/identity-files': { post: { tags: ['Documenti'], summary: 'Salva insieme carta identita fronte/retro e patente fronte/retro', requestBody: { required: true, content: { 'multipart/form-data': { schema: { $ref: '#/components/schemas/SaveIdentityDocumentsMultipartRequest' } }, 'application/json': { schema: { $ref: '#/components/schemas/SaveIdentityDocumentsJsonRequest' } } } }, responses: created() } },
    '/documents/{id}': { get: { tags: ['Documenti'], summary: 'Dettaglio documento salvato', parameters: [idParam()], responses: ok() }, delete: { tags: ['Documenti'], summary: 'Soft delete documento salvato', parameters: [idParam()], responses: ok() } },
    '/documents/{id}/download': { get: { tags: ['Documenti'], summary: 'Download file documento salvato', parameters: [idParam()], responses: { '200': { description: 'File documento', content: { 'application/octet-stream': { schema: { type: 'string', format: 'binary' } } } } } } },
    '/contract-templates': crud('Contratti', 'template contratto', 'CreateContractTemplateRequest'),
    '/contract-templates/{code}': crudByCode('Contratti', 'template contratto', 'UpdateContractTemplateRequest'),
    '/contract-templates/default': { put: { tags: ['Contratti'], summary: 'Imposta template contratto predefinito', requestBody: body('SetDefaultContractTemplateRequest'), responses: ok() } },
    '/contracts/placeholders': { get: { tags: ['Contratti'], summary: 'Lista placeholder disponibili per i template contratto', responses: { '200': { description: 'Placeholder disponibili', content: { 'application/json': { schema: { $ref: '#/components/schemas/ContractPlaceholdersResponse' } } } } } } },
    '/contracts/render-html': { post: { tags: ['Contratti'], summary: 'Genera HTML contratto da bookingId con placeholder risolti, logo/timbro e area firma cliccabile', requestBody: body('RenderContractHtmlRequest'), responses: ok() } },
    '/contracts/generate': { post: { tags: ['Contratti'], summary: 'Genera PDF contratto da bookingId e template', requestBody: body('GenerateContractRequest'), responses: { '200': { description: 'PDF contratto', content: { 'application/pdf': { schema: { type: 'string', format: 'binary' } } } } } } },
    '/contracts/sign': { post: { tags: ['Contratti'], summary: 'Genera PDF contratto firmato apponendo la firma cliente sul placeholder [[FIRMA_CLIENTE]]', requestBody: body('SignContractRequest'), responses: { '200': { description: 'PDF contratto firmato', content: { 'application/pdf': { schema: { type: 'string', format: 'binary' } } } } } } },
    '/contracts/signed-documents': { post: { tags: ['Contratti'], summary: 'Salva documento contratto firmato su storage e registra i metadati', requestBody: body('SaveSignedContractDocumentRequest'), responses: created() } }
  },
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    parameters: { Id: idParam() },
    schemas: {
      ErrorResponse: obj(['code','message','requestId'], { code: str(), message: str(), requestId: str(), details: { type: 'array', items: { type: 'object' } } }),
      RegisterRequest: obj(['nomeSocieta', 'email', 'password', 'datiFatturazione'], { nomeSocieta: str(), email: email(), password: { type: 'string', format: 'password', minLength: 8 }, datiFatturazione: obj(['partitaIva', 'codiceFiscaleSocieta', 'ragioneSociale', 'indirizzoSedeLegale', 'codiceUnivoco'], { partitaIva: str(), codiceFiscaleSocieta: str(), ragioneSociale: str(), indirizzoSedeLegale: str(), codiceUnivoco: str() }) }),
      LoginRequest: obj(['email', 'password'], { email: email(), password: { type: 'string', format: 'password' } }),
      SearchTextRequest: obj([], { filter: str(), pagination: { $ref: '#/components/schemas/Pagination' } }), Pagination: obj([], { page: { type: 'integer', example: 1 }, pageSize: { type: 'integer', example: 20 } }),
      CreateClientRequest: obj(['nome','cognome','sesso','dataNascita','luogoNascita','codiceFiscale','indirizzoResidenza','luogoRilascioCartaIdentita','numeroCartaIdentita','luogoRilascioPatente','numeroPatente','telefono'], clientProps()), UpdateClientRequest: obj([], clientProps()),
      FiscalCodeRequest: obj(['nome','cognome','dataNascita','luogoNascita','sesso'], { nome: str(), cognome: str(), dataNascita: dt(), luogoNascita: str(), sesso: { type: 'string', enum: ['M','F'] } }), AddressAutocompleteRequest: obj(['filter'], { filter: str(), limit: { type: 'integer', example: 10 } }),
      CreateVehicleRequest: obj(['tipo','marca','modello','targa','dataImmatricolazione','alimentazione','costoGiornaliero'], { tipo: { type: 'string', enum: ['AUTO','FURGONE'] }, marca: str(), modello: str(), targa: str(), dataImmatricolazione: dt(), alimentazione: { type: 'string', enum: ['BENZINA','DIESEL','GPL','METANO','IBRIDA','ELETTRICA'] }, costoGiornaliero: num(), lunghezza: num(), larghezza: num(), altezza: num(), kmAttuali: { type: 'integer' } }), UpdateVehicleRequest: obj([], { tipo: str(), marca: str(), modello: str(), targa: str(), costoGiornaliero: num() }),
      VehicleDateRangeRequest: obj(['targa','dataInizioContratto','dataFineContratto'], { targa: str(), dataInizioContratto: dt(), dataFineContratto: dt() }), AvailableVehiclesRequest: obj(['tipo','dataInizioContratto','dataFineContratto'], { tipo: { type: 'string', enum: ['AUTO','FURGONE'] }, dataInizioContratto: dt(), dataFineContratto: dt() }),
      PaymentMethod: { type: 'string', enum: ['CONTANTI','CARTA_CREDITO','CARTA_DEBITO','BONIFICO','ASSEGNO','ALTRO'] },
      DepositPaymentMethod: { type: 'string', enum: ['CONTANTI','CARTA','BONIFICO'] },
      CreateBookingRequest: obj(['veicoloId','dataInizioContratto','dataFineContratto','prezzo','mileagePackageId','nomeOperatore'], { clienteId: uuid(), nuovoCliente: { $ref: '#/components/schemas/CreateClientRequest' }, conducenteAggiuntivoId: uuid(), nuovoConducenteAggiuntivo: { $ref: '#/components/schemas/CreateClientRequest' }, billingDataId: uuid(), nuoviDatiFatturazione: { $ref: '#/components/schemas/CreateBillingDataWithoutClientRequest' }, veicoloId: uuid(), dataInizioContratto: dt(), dataFineContratto: dt(), prezzo: num(), metodoPagamento: { $ref: '#/components/schemas/PaymentMethod' }, dataEmissioneFattura: dt(), mileagePackageId: uuid(), nomeOperatore: str(), operatorId: uuid(), coperturaAssicurativaId: uuid(), serviziAggiuntiviIds: { type: 'array', items: uuid() }, kmInizio: { type: 'integer' }, note: str() }), UpdateBookingRequest: obj([], { clienteId: uuid(), conducenteAggiuntivoId: uuid(), billingDataId: uuid(), dataEmissioneFattura: dt(), metodoPagamento: { $ref: '#/components/schemas/PaymentMethod' }, mileagePackageId: uuid(), serviziAggiuntiviIds: { type: 'array', items: uuid() } }), SearchBookingRequest: obj([], { filter: { type: 'object' }, pagination: { $ref: '#/components/schemas/Pagination' } }), FindByFineRequest: obj(['targa','dataMulta'], { targa: str(), dataMulta: dt() }),
      BookingDeliveryRequest: obj(['importoCauzione','metodoPagamentoCauzione','livelloCarburanteConsegna','kmConsegna'], { importoCauzione: num(), metodoPagamentoCauzione: { $ref: '#/components/schemas/DepositPaymentMethod' }, codicePreautorizzazioneCauzione: str(), livelloCarburanteConsegna: { type: 'integer' }, kmConsegna: { type: 'integer' } }),
      BookingReturnDamageRequest: obj(['x','y'], { note: str(), x: { type: 'integer' }, y: { type: 'integer' }, stato: { type: 'string', enum: ['APERTO','RIPARATO'] } }),
      BookingReturnRequest: obj(['livelloCarburanteRiconsegna','kmRiconsegna'], { livelloCarburanteRiconsegna: { type: 'integer' }, kmRiconsegna: { type: 'integer' }, cauzioneRestituita: { type: 'boolean' }, cauzioneTrattenuta: { type: 'boolean' }, metodoPagamentoCauzione: { $ref: '#/components/schemas/DepositPaymentMethod' }, codicePreautorizzazioneCauzione: str(), noteRiconsegna: str(), metodoPagamentoPenali: { $ref: '#/components/schemas/PaymentMethod' }, importoPenali: num(), nuoviDanni: { type: 'array', items: { $ref: '#/components/schemas/BookingReturnDamageRequest' } } }),
      CreateBillingDataRequest: obj(['clienteId','codiceFiscale','ragioneSociale','indirizzoSedeLegale'], billingProps(true)), CreateBillingDataWithoutClientRequest: obj(['codiceFiscale','ragioneSociale','indirizzoSedeLegale'], billingProps(false)), UpdateBillingDataRequest: obj([], billingProps(true)), SearchBillingDataRequest: obj([], { clienteId: uuid(), filter: str(), pagination: { $ref: '#/components/schemas/Pagination' } }),
      CreateFineRequest: obj(['targa','dataMulta','importo','dataNotifica','luogoInfrazione'], { targa: str(), dataMulta: dt(), importo: num(), dataNotifica: dt(), luogoInfrazione: str(), dataRinotifica: dt(), note: str() }), UpdateFineRequest: obj([], { importo: num(), dataNotifica: dt(), luogoInfrazione: str(), dataRinotifica: dt(), note: str() }), SearchFineRequest: obj([], { filter: { type: 'object' }, pagination: { $ref: '#/components/schemas/Pagination' } }),
      CreateDamageRequest: obj(['x','y'], { note: str(), x: { type: 'integer', example: 300 }, y: { type: 'integer', example: 150 }, dataAggiunta: dt() }), UpdateDamageRequest: obj([], { note: str(), x: { type: 'integer' }, y: { type: 'integer' } }), SearchDamageRequest: obj([], { filter: { type: 'object' }, pagination: { $ref: '#/components/schemas/Pagination' } }),
      CreateCoverageRequest: obj(['nome'], { nome: str(), costoImportoFisso: num(), costoPercentuale: num(), franchigiaRca: num(), franchigiaKasko: num(), franchigiaFurtoIncendio: num() }), UpdateCoverageRequest: obj([], { nome: str(), costoImportoFisso: num(), costoPercentuale: num(), franchigiaRca: num(), franchigiaKasko: num(), franchigiaFurtoIncendio: num() }),
      CreateMileagePackageRequest: obj(['nome'], costProps()), UpdateMileagePackageRequest: obj([], costProps()), CreateAdditionalServiceRequest: obj(['nome'], { ...costProps().properties, descrizione: str() }), UpdateAdditionalServiceRequest: obj([], { ...costProps().properties, descrizione: str() }),
      RentalSettingsRequest: obj([], { costoConducenteAggiuntivoImportoFisso: num(), costoConducenteAggiuntivoPercentuale: num(), cauzioneStandard: num(), costoKmEccedenza: num(), penaleCarburante: num() }),
      CargosPortalConfigRequest: obj(['username','password','apiKey'], { username: str(), password: { type: 'string', format: 'password' }, apiKey: { type: 'string', format: 'password' } }),
      UpdateCargosPortalConfigRequest: obj([], { username: str(), password: { type: 'string', format: 'password' }, apiKey: { type: 'string', format: 'password' } }),
      CargosPortalConfigResponse: obj([], { companyId: uuid(), username: str(), hasPassword: { type: 'boolean' }, hasApiKey: { type: 'boolean' }, createdAt: dt(), createdBy: str(), updatedAt: dt(), updatedBy: str(), deletedAt: dt(), deletedBy: str() }),
      CreateOperatorRequest: obj(['nome'], { nome: str(), cognome: str(), telefono: str(), email: email(), attivo: { type: 'boolean' } }),
      DocumentType: { type: 'string', enum: ['CIE_FRONT','CIE_BACK','DRIVING_LICENSE_FRONT','DRIVING_LICENSE_BACK','SIGNED_CONTRACT','CONTRACT_PDF','OTHER'] },
      SaveDocumentMultipartRequest: obj(['type','file'], { type: { $ref: '#/components/schemas/DocumentType' }, file: file(), fileName: str(), bookingId: str(), clientId: str(), contractDocumentId: str(), metadata: str() }),
      SaveDocumentJsonRequest: obj(['type','fileBase64'], { type: { $ref: '#/components/schemas/DocumentType' }, fileBase64: str(), fileName: str(), mimeType: str(), bookingId: str(), clientId: str(), contractDocumentId: str(), metadata: { type: 'object', additionalProperties: true } }),
      SaveIdentityDocumentsMultipartRequest: obj(['cieFront','cieBack','drivingLicenseFront','drivingLicenseBack'], { cieFront: file(), cieBack: file(), drivingLicenseFront: file(), drivingLicenseBack: file(), bookingId: str(), clientId: str(), metadata: str() }),
      SaveIdentityDocumentsJsonRequest: obj(['cieFront','cieBack','drivingLicenseFront','drivingLicenseBack'], { cieFront: str(), cieBack: str(), drivingLicenseFront: str(), drivingLicenseBack: str(), bookingId: str(), clientId: str(), metadata: { type: 'object', additionalProperties: true } }),
      CreateContractTemplateRequest: obj(['name','html'], { name: str(), html: str(), isDefault: { type: 'boolean' } }),
      UpdateContractTemplateRequest: obj([], { name: str(), html: str() }),
      SetDefaultContractTemplateRequest: obj(['code'], { code: str() }),
      SignatureInput: obj([], { dataUrl: str(), base64: str(), url: str(), mimeType: str(), width: str(), height: str(), alt: str(), className: str(), style: str() }),
      ContractPlaceholderItem: obj(['key'], { key: str(), label: str(), description: str(), example: str(), category: str() }),
      ContractPlaceholdersResponse: obj(['items'], { items: { type: 'array', items: { $ref: '#/components/schemas/ContractPlaceholderItem' } } }),
      GenerateContractRequest: obj(['bookingId'], { bookingId: uuid(), templateCode: str(), placeholder: { type: 'object', additionalProperties: true, description: 'Override opzionali. Normalmente non necessario: i placeholder vengono recuperati da backend tramite bookingId.' }, signature: obj([], { client: { oneOf: [str(), { $ref: '#/components/schemas/SignatureInput' }] } }), pdf: { type: 'object', additionalProperties: true } }),
      RenderContractHtmlRequest: obj(['bookingId'], { bookingId: uuid(), templateCode: str(), placeholder: { type: 'object', additionalProperties: true, description: 'Override opzionali. Normalmente non necessario: i placeholder vengono recuperati da backend tramite bookingId.' }, signArea: obj([], { client: obj([], { text: str(), className: str(), style: str() }) }) }),
      SignContractRequest: obj(['bookingId','signature'], { bookingId: uuid(), templateCode: str(), placeholder: { type: 'object', additionalProperties: true, description: 'Override opzionali. Normalmente non necessario: i placeholder vengono recuperati da backend tramite bookingId.' }, signature: obj(['client'], { client: { oneOf: [str(), { $ref: '#/components/schemas/SignatureInput' }] } }), pdf: { type: 'object', additionalProperties: true } }),
      SaveSignedContractDocumentRequest: obj(['bookingId','signature'], { bookingId: uuid(), templateCode: str(), placeholder: { type: 'object', additionalProperties: true, description: 'Override opzionali. Normalmente non necessario: i placeholder vengono recuperati da backend tramite bookingId.' }, signature: obj(['client'], { client: { oneOf: [str(), { $ref: '#/components/schemas/SignatureInput' }] } }), pdf: { type: 'object', additionalProperties: true }, fileName: str(), clientId: str(), metadata: { type: 'object', additionalProperties: true } })
    }
  }
};
function idParam() { return { name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }; }
function ok() { return { '200': { description: 'OK' } }; } function created() { return { '201': { description: 'Creato' } }; }
function body(schema: string) { return { required: true, content: { 'application/json': { schema: { $ref: `#/components/schemas/${schema}` } } } }; }
function postBody(tag: string, summary: string, schema: string) { return { post: { tags: [tag], summary, requestBody: body(schema), responses: ok() } }; }
function crud(tag: string, label: string, schema: string) { return { get: { tags: [tag], summary: `Lista ${label}`, responses: ok() }, post: { tags: [tag], summary: `Crea ${label}`, requestBody: body(schema), responses: created() } }; }
function crudById(tag: string, label: string, schema: string) { return { get: { tags: [tag], summary: `Dettaglio ${label}`, parameters: [idParam()], responses: ok() }, patch: { tags: [tag], summary: `Modifica ${label}`, parameters: [idParam()], requestBody: body(schema), responses: ok() }, delete: { tags: [tag], summary: `Elimina ${label}`, parameters: [idParam()], responses: ok() } }; }
function patchOnly(tag: string, label: string, schema: string) { return { patch: { tags: [tag], summary: `Modifica ${label}`, parameters: [idParam()], requestBody: body(schema), responses: ok() } }; }
function codeParam() { return { name: 'code', in: 'path', required: true, schema: { type: 'string' } }; }
function queryParam(name: string) { return { name, in: 'query', required: false, schema: { type: 'string' } }; }
function crudByCode(tag: string, label: string, schema: string) { return { get: { tags: [tag], summary: `Dettaglio ${label}`, parameters: [codeParam()], responses: ok() }, patch: { tags: [tag], summary: `Modifica ${label}`, parameters: [codeParam()], requestBody: body(schema), responses: ok() }, delete: { tags: [tag], summary: `Elimina ${label}`, parameters: [codeParam()], responses: ok() } }; }
function str() { return { type: 'string' }; } function file() { return { type: 'string', format: 'binary' }; } function email() { return { type: 'string', format: 'email' }; } function uuid() { return { type: 'string', format: 'uuid' }; } function dt() { return { type: 'string', format: 'date-time' }; } function num() { return { type: 'number' }; }
function obj(required: string[], properties: any) { return { type: 'object', required, properties }; }
function clientProps() { return { nome: str(), cognome: str(), sesso: { type: 'string', enum: ['M','F'] }, dataNascita: dt(), luogoNascita: str(), codiceFiscale: str(), indirizzoResidenza: str(), luogoRilascioCartaIdentita: str(), numeroCartaIdentita: str(), dataRilascioCartaIdentita: dt(), dataScadenzaCartaIdentita: dt(), luogoRilascioPatente: str(), numeroPatente: str(), dataRilascioPatente: dt(), dataScadenzaPatente: dt(), telefono: str(), email: email() }; }
function billingProps(withClient: boolean) { return { ...(withClient ? { clienteId: uuid() } : {}), partitaIva: str(), codiceFiscale: str(), ragioneSociale: str(), indirizzoSedeLegale: str(), codiceUnivoco: str(), pec: str(), email: email() }; }
function costProps() { return obj(['nome'], { nome: str(), costoImportoFisso: num(), costoPercentuale: num(), attivo: { type: 'boolean' } }); }
